name: netflix-api Actions
run-name: ${{ github.actor }} is checking the netflix-api
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: netflix-api
        run: mvn clean install