name: one-piece-api Actions
run-name: ${{ github.actor }} is checking the one-piece-api
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Change to specific directory
        run: cd one-piece-api/
      - name: Build with Maven
        run: mvn clean install